name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - git+https://github.com/openai/whisper.git
    - pandas
    - matplotlib
